MutationsPhysical = {
    ("Zwierzęce nogi", "Szybkość +1"): 5,
    ("Otyłość", "Szybkość –1, Siła +5, Wytrzymałość +5"): 5,
    ("Wydłużone palce", "Zręczność +10"): 5,
    ("Wychudzone ciało", "Siła –10, Zwinność +5"): 5,
    ("Ogromne oko", "+10 do wszystkich związanych ze wzrokiem Testów Percepcji"): 5,
    ("Dodatkowe stawy w nogach", "Zwinność +5"): 5,
    ("Dodatkowe usta", "Rzuć kośćmi, by ustalić Miejsce Trafienia, w którym się pojawią"): 5,
    ("Mięsista macka", "Postać zyskuje Cechę Stworzenia Macki, patrz strona 339"): 5,
    ("Świecąca skóra", "Blask porównywalny z płomieniem świecy"): 5,
    ("Nieludzka uroda", "Ogłada +10, rany zawsze goją się bez blizn"): 5,
    ("Odwrócona twarz", "–20 do testów Ogłady"): 5,
    ("Stalowa skóra", "+2 Punkty Pancerza na wszystkich Miejscach Trafienia, Zwinność –10"): 5,
    ("Zwisający jęzor", "–10 do wszystkich Testów Języka wymagających mówienia"): 5,
    ("Niejednolite opierzenie", "Rzuć dwukrotnie, by ustalić Miejsce Trafienia porosłe pierzem"): 5,
    ("Krótkie nogi", "Szybkość –1"): 5,
    ("Kolczaste łuski", "+1 Punkt Pancerza na wszystkich Miejscach Trafienia"): 5,
    ("Nierówne rogi", "+1 Punkt Pancerza na głowie. Postać liczy się, jakby posiadała Cechę Stworzenia Broń o współczynniku obrażeń +BS"): 5,
    ("Sącząca się ropa", "Rzuć k100, by ustalić Miejsce Trafienia, z którego się sączy"): 5,
    ("Wibrysy", "+10 do Tropienia"): 5,
    ("Decyzja MG", "MG wybiera mutację albo Cechę Stworzenia potwora"): 5,
}

MutationsMental = {
    ("Odrażające zachcianki", "Ogłada –5, Siła Woli –5"): 5,
    ("Wewnętrzna bestia", "Siła Woli +10, Ogłada –5, Inteligencja –5"): 5,
    ("Chaotyczne sny", "Postać przez pierwsze 2 godziny po śnie uznawana jest za Zmęczoną"): 5,
    ("Nieustanne dreszcze", "Inicjatywa –5, Zręczność –5"): 5,
    ("Mitomania", "Inicjatywa –5, Siła Woli –5"): 5,
    ("Straszny niepokój", "Siła Woli –10"): 5,
    ("Nienawistne popędy", "Wrogość (patrz Psychologia) wobec wszystkich istot poza rasą postaci"): 5,
    ("Bezduszność", "Siła Woli +10, Ogłada –10"): 5,
    ("Zazdrosne myśli", "Ogłada –10"): 5,
    ("Strach przed samotnością", "–10 do wszelkich Testów wykonywanych w samotności"): 5,
    ("Blokada psychiczna", "Inteligencja –10"): 5,
    ("Bluźniercze popędy", "Siła Woli –10, Zwinność +10"): 5,
    ("Chwiejne morale", "Za każdym razem, gdy postaci nie powiedzie się Test Siły Woli, otrzymuje 1 poziom paniki"): 5,
    ("Paranoja", "Inicjatywa –5, Inteligencja –5"): 5,
    ("Uzależnienie od adrenaliny", "Siła Woli +10, Inicjatywa –10"): 5,
    ("Dręczące wizje", "Inicjatywa –10"): 5,
    ("Kompletny świr", "Ogłada –20, Siła Woli +10"): 5,
    ("Złe zamiary", "–10 do Testów, które nie mają na celu krzywdzenia innych; "
                    "+10, jeśli zamiarem jest wyrządzenie krzywdy"): 5,
    ("Bezbożny szał", "Szał Bojowy (patrz Psychologia), Walka Wręcz +10"): 5,
    ("Drżączka", "Zwinność +5, Ogłada –5"): 5,
}

MutationsAdvanced = {
    ("Albinos", ""): 5,
    ("Atrofia", ""): 5,
    ("Bestia o tysiącu...", ""): 5,
    ("Bezgłowy", ""): 5,
    ("Bezpodstawna nienawiść", ""): 5,
    ("Bezrozumny", ""): 5,
    ("Chaosołak", ""): 5,
    ("Chwytny ogon", ""): 5,
    ("Cielesna korona", ""): 5,
    ("Ciernie", ""): 5,
    ("Cuchnący dotyk", ""): 5,
    ("Czarna skóra", ""): 5,
    ("Czworonożny/Dwunożny", ""): 5,
    ("Demoniczny byt", ""): 5,
    ("Długa szyja", ""): 5,
    ("Długi nos", ""): 5,
    ("Długi kolce", ""): 5,
    ("Długie nogi", ""): 5,
    ("Do góry nogami", ""): 5,
    ("Dodatkowa kończyna", ""): 5,
    ("Dodatkowe oko", ""): 5,
    ("Dodatkowe palce", ""): 5,
    ("Dodatkowe ucho", ""): 5,
    ("Dodatkowe usta", ""): 5,
    ("Dodatkowe nos", ""): 5,
    ("Drgawki", ""): 5,
    ("Dziób", ""): 5,
    ("Dziwny chód", ""): 5,
    ("Dziwny głos", ""): 5,
    ("Fałszywy demon", ""): 5,
    ("Futro", ""): 5,
    ("Garb", ""): 5,
    ("Gęsta grzywa", ""): 5,
    ("Gęste futro", ""): 5,
    ("Giętkie kończyny", ""): 5,
    ("Głowonóg", ""): 5,
    ("Głupawy", ""): 5,
    ("Gnijące ciało", ""): 5,
    ("Grzebień kostny", ""): 5,
    ("Grzybnia", ""): 5,
    ("Gwoźdiogłowy", ""): 5,
    ("Hipnotyczny trans", ""): 5,
    ("Hipnotyzujące spojrzenie", ""): 5,
    ("Jednonogi", ""): 5,
    ("Jednooki", ""): 5,
    ("Kipiele", ""): 5,
    ("Kłujący jęzor", ""): 5,
    ("Kły", ""): 5,
    ("Kły jadowe", ""): 5,
    ("Kolczasty ogon", ""): 5,
    ("Kolorowa skóra", ""): 5,
    ("Kopyta", ""): 5,
    ("Kostropata skóra", ""): 5,
    ("Krótkie nogi", ""): 5,
    ("Kryształowe ciało", ""): 5,
    ("Kwasowa wydzielina", ""): 5,
    ("Kwasowe wymioty", ""): 5,
    ("Lewitacja", ""): 5,
    ("Łuskowata skóra", ""): 5,
    ("Macki zamiast ramion", ""): 5,
    ("Mackowate palce", ""): 5,
    ("Magiczna moc", ""): 5,
    ("Marionetka", ""): 5,
    ("Mechanoid", ""): 5,
    ("Metaliczna skóra", ""): 5,
    ("Metalowe ciało", ""): 5,
    ("Mieszaniec", ""): 5,
    ("Mistrz broni", ""): 1,
    ("Myśląca narośl", ""): 5,
    ("Niekontrolowane gazy", ""): 5,
    ("Nienaturalne łaknienie", ""): 5,
    ("Niestabilność czasowa", ""): 5,
    ("Nietypowe ubarwienie", ""): 5,
    ("Nieuzasadniona fobia", ""): 5,
    ("Niewidzialność", ""): 5,
    ("Niewrażliwość na magię", ""): 5,
    ("Nieznaczna zmiana wyglądu", ""): 5,
    ("Oblicze gorejącej czaszki", ""): 5,
    ("Obłęd", ""): 5,
    ("Obwiosły", ""): 5,
    ("Ociekający śluzem", ""): 5,
    ("Oczy na szypułkach", ""): 5,
    ("Odłączalne kończyny", ""): 5,
    ("Odór", ""): 5,
    ("Odpornośc na magię", ""): 5,
    ("Odporny", ""): 5,
    ("Ogniste ciało", ""): 5,
    ("Ogniste ciało", ""): 5,
    ("Ogon", ""): 5,
    ("Ogon skarpiona", ""): 5,
    ("Ogromna narośl", ""): 5,
    ("Olbrzymia głowa", ""): 5,
    ("Organ Chaosu", ""): 5,
    ("Osiłek", ""): 5,
    ("Pasożytniczy bliźniak", ""): 5,
    ("Pazury", ""): 5,
    ("Plucie kwasem", ""): 5,
    ("Podmieniec", ""): 5,
    ("Podwojenie", ""): 5,
    ("Polipy", ""): 5,
    ("Pomiot Chaosu", ""): 5,
    ("Ponętny", ""): 5,
    ("Porażający dotyk", ""): 5,
    ("Potworna otyłość", ""): 5,
    ("Potworny wygląd", ""): 5,
    ("Powielenie", ""): 5,
    ("Prymityw", ""): 5,
    ("Przeniesienie kończyny", ""): 5,
    ("Przerośnięta część ciałą", ""): 5,
    ("Przezroczysta skóra", ""): 5,
    ("Przyssawki", ""): 5,
    ("Przytłaczający intelekt", ""): 5,
    ("Ptasie odnóża", ""): 5,
    ("Rączy", ""): 5,
    ("Regeneracja", ""): 5,
    ("Robaczywy", ""): 5,
    ("Rogi", ""): 5,
    ("Rozrost", ""): 5,
    ("Rój much", ""): 5,
    ("Siewca zarazy", ""): 5,
    ("Silne nogi", ""): 5,
    ("Skrzydła", ""): 5,
    ("Spaczeniowy szał", ""): 5,
    ("Spaczony umysł", ""): 5,
    ("Spiczastogłowy", ""): 5,
    ("Strach przed krwią", ""): 5,
    ("Syrena", ""): 5,
    ("Szalony wojownik", ""): 5,
    ("Szczypce", ""): 5,
    ("Ślimacze ciało", ""): 5,
    ("Świecąca skóra", ""): 5,
    ("Tchórzostwo", ""): 5,
    ("Telekineza", ""): 5,
    ("Telepatia", ""): 5,
    ("Teleportacja", ""): 5,
    ("Trąba", ""): 5,
    ("Trupia czaszka", ""): 5,
    ("Twarda skóra", ""): 5,
    ("Twarz bez rysów", ""): 5,
    ("Uderzające podobiństwo", ""): 5,
    ("Upierzenie", ""): 5,
    ("Utrata umysłu", ""): 5,
    ("Uzależnienie", ""): 5,
    ("Wampir", ""): 5,
    ("Wielkie uszy", ""): 5,
    ("Wielogłowy", ""): 5,
    ("Wieloręki", ""): 5,
    ("Wrzody", ""): 5,
    ("Wychudła sylwetka", ""): 5,
    ("Wyłupiaste oczy", ""): 5,
    ("Zanik", ""): 5,
    ("Zanik kończyny", ""): 5,
    ("Zanik kości", ""): 5,
    ("Zatracenie duszy", ""): 5,
    ("Zła krew", ""): 5,
    ("Złe oko", ""): 5,
    ("Złudzenie normalności", ""): 5,
    ("Zły", ""): 5,
    ("Zmiennokształtny", ""): 4,
    ("Zniekształcona twarz", ""): 5,
    ("Zwierzęca mutacja", ""): 5,
    ("Zwierzęce odnóża", ""): 5,
    ("Zwierzęcy pysk", ""): 5,
    ("Zwierzęcy tułów", ""): 5,
    ("Zwierzęcy wygląd", ""): 5,
    ("Zwinny", ""): 5,
    ("Żądza krwii", ""): 5,
    ("Żelazna skóra", ""): 5,
    ("Żywa broń", ""): 5,
    ("Żywy szkielet", ""): 5,
    ("Rzuć dwa razy", ""): 5,
    ("Rzuć trzy razy", ""): 5,
    ("Wybór MG", ""): 5,
}
